import { describe, expect, it } from 'vitest'
import { MAX_LOCKFILE_BYTES, parseCargoLock } from '../dependencies'

const SAMPLE_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "soroban-sdk"
version = "21.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abcdef0123456789"
dependencies = [
 "soroban-env-common",
]

[[package]]
name = "soroban-env-common"
version = "21.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "local-only"
version = "0.1.0"
`

describe('parseCargoLock', () => {
  it('extracts all packages with their fields', () => {
    const inventory = parseCargoLock(SAMPLE_LOCK)
    expect(inventory.packageCount).toBe(3)
    expect(inventory.dependencies[0]).toEqual({
      name: 'soroban-sdk',
      version: '21.0.0',
      source: 'registry+https://github.com/rust-lang/crates.io-index',
      checksum: 'abcdef0123456789',
    })
    expect(inventory.dependencies[2]).toEqual({ name: 'local-only', version: '0.1.0', source: null, checksum: null })
    expect(inventory.parseWarnings).toHaveLength(0)
  })

  it('warns on a malformed package block instead of throwing', () => {
    const text = `[[package]]\nversion = "1.0.0"\n`
    const inventory = parseCargoLock(text)
    expect(inventory.packageCount).toBe(0)
    expect(inventory.parseWarnings).toHaveLength(1)
    expect(inventory.parseWarnings[0]).toMatch(/missing a name or version/)
  })

  it('returns an empty inventory for empty input', () => {
    const inventory = parseCargoLock('')
    expect(inventory.packageCount).toBe(0)
    expect(inventory.dependencies).toHaveLength(0)
  })

  it('rejects an oversized lockfile before parsing', () => {
    const huge = 'x'.repeat(MAX_LOCKFILE_BYTES + 1)
    const inventory = parseCargoLock(huge)
    expect(inventory.packageCount).toBe(0)
    expect(inventory.parseWarnings[0]).toMatch(/exceeds/)
  })

  it('does not choke on a lockfile with unrelated tables interspersed', () => {
    const text = `[[package]]\nname = "a"\nversion = "1.0.0"\n\n[profile.release]\nopt-level = 3\n\n[[package]]\nname = "b"\nversion = "2.0.0"\n`
    const inventory = parseCargoLock(text)
    expect(inventory.packageCount).toBe(2)
    expect(inventory.dependencies.map((d) => d.name)).toEqual(['a', 'b'])
  })
})
